---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: node1
  ansible_verbose: true
  ansible_verbosity: 2
  ansible_connection: ssh
  requirements_path: requirements.yaml

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: dliappis/ubuntu-devopsci:14.04
      privileged: true
      provision_command:
        - mkdir -p /home/kitchen/.ansible/tmp && chmod 777 /home/kitchen/.ansible/tmp
      use_sudo: false

suites:
  - name: default
    provisioner:
      playbook: test/integration/default/default.yml
    run_list:
    attributes:
